### ISSUE TITLE
Gemfile installation requires `require`

### ISSUE THREAD

**Issue by jpmoral** [johnnyshields/naturalsort#4]
I had to use `gem 'naturalsort', require: 'natural_sort'` to get it working.

Not sure if having a `naturalsort.rb` that just does `require 'natural_sort'` is the best way to address this or if there's something better.

**Comment by johnnyshields** [comment]
Yeah I think we need to add `naturalsort.rb` as you say. Can you raise a PR?

**Comment by jpmoral** [comment]
Sure.

**Comment by jpmoral** [comment]
Strange, I cannot reproduce the issue with a Gemfile that points to a local copy of the gem.
